#+TITLE: xelisp
#+AUTHOR: Jason Lewis

Exercism problems in Emacs Lisp.

** Contributing to The Emacs Lisp Track

*** Contributing Guide

Please see the [[https://github.com/exercism/x-api/blob/master/CONTRIBUTING.md#the-exercise-data)][contributing guide]].
This describes how all the language tracks are put together,
as well as details about the common metadata, and high-level
information about contributing to existing problems and adding new problems.

*** Issues

Feel free to file any issues on the [[https://github.com/exercism/xelisp/issues][xelisp issue tracker]] for problems of
any size. Feel free to report typographical errors or poor wording for
example. You can greatly help improve the quality of the exercises by
filing reports of invalid solutions that pass tests or of valid solutions
that fail tests.

New exercises or changes to existing ones can be submitted via a pull
request. You will need a GitHub account and you will need to fork
[[https://github.com/exercism/xelisp][exercism/xelisp]] to your account. See GitHub Help if you are unfamiliar
with the process.


** License

The MIT License (MIT)

Copyright (c) 2015 Katrina Owen, _@kytrinyx.com

*** GNU Emacs icon
The GNU Emacs icon was designed by Andrew Zhilin and is licensed under the Creative Commons Attribution-ShareAlike 3.0 License.
We have modified the GNU Emacs icon to create the Emacs Lisp icon for Exercism.
