;;; relative-distance-test.el --- Tests for Relative Distance (exercism)  -*- lexical-binding: t; -*-

;;; Commentary:

;;; Code:


(load-file "relative-distance.el")
(declare-function degree-of-separation "relative-distance.el" (family-tree person-a person-b))


(ert-deftest direct-parent-child-relation ()
  (should (= 1 (degree-of-separation '(
                    ("Vera" "Tomoko")
                    ("Tomoko" "Aditi"))
                  "Vera" "Tomoko"))))


(ert-deftest sibling-relationship ()
  (should (= 1 (degree-of-separation '(
                    ("Dalia" "Olga" "Yassin"))
                  "Olga" "Yassin"))))


(ert-deftest two-degrees-of-separation-grandchild ()
  (should (= 2 (degree-of-separation '(
                    ("Khadija" "Mateo")
                    ("Mateo" "Rami"))
                  "Khadija" "Rami"))))


(ert-deftest unrelated-individuals ()
  (should-not (degree-of-separation '(
                    ("Priya" "Rami")
                    ("Kaito" "Elif"))
                  "Priya" "Kaito")))


(ert-deftest complex-graph-cousins ()
  (should (= 9 (degree-of-separation '(
                    ("Aiko" "Bao" "Carlos")
                    ("Bao" "Dalia" "Elias")
                    ("Carlos" "Fatima" "Gustavo")
                    ("Dalia" "Hassan" "Isla")
                    ("Elias" "Javier")
                    ("Fatima" "Khadija" "Liam")
                    ("Gustavo" "Mina")
                    ("Hassan" "Noah" "Olga")
                    ("Isla" "Pedro")
                    ("Javier" "Quynh" "Ravi")
                    ("Khadija" "Sofia")
                    ("Liam" "Tariq" "Uma")
                    ("Mina" "Viktor" "Wang")
                    ("Noah" "Xiomara")
                    ("Olga" "Yuki")
                    ("Pedro" "Zane" "Aditi")
                    ("Quynh" "Boris")
                    ("Ravi" "Celine")
                    ("Sofia" "Diego" "Elif")
                    ("Tariq" "Farah")
                    ("Uma" "Giorgio")
                    ("Viktor" "Hana" "Ian")
                    ("Wang" "Jing")
                    ("Xiomara" "Kaito")
                    ("Yuki" "Leila")
                    ("Zane" "Mateo")
                    ("Aditi" "Nia")
                    ("Boris" "Oscar")
                    ("Celine" "Priya")
                    ("Diego" "Qi")
                    ("Elif" "Rami")
                    ("Farah" "Sven")
                    ("Giorgio" "Tomoko")
                    ("Hana" "Umar")
                    ("Ian" "Vera")
                    ("Jing" "Wyatt")
                    ("Kaito" "Xia")
                    ("Leila" "Yassin")
                    ("Mateo" "Zara")
                    ("Nia" "Antonio")
                    ("Oscar" "Bianca")
                    ("Priya" "Cai")
                    ("Qi" "Dimitri")
                    ("Rami" "Ewa")
                    ("Sven" "Fabio")
                    ("Tomoko" "Gabriela")
                    ("Umar" "Helena")
                    ("Vera" "Igor")
                    ("Wyatt" "Jun")
                    ("Xia" "Kim")
                    ("Yassin" "Lucia")
                    ("Zara" "Mohammed"))
                  "Dimitri" "Fabio"))))


(ert-deftest complex-graph-no-shortcut-far-removed-nephew ()
  (should (= 14 (degree-of-separation '(
                    ("Aiko" "Bao" "Carlos")
                    ("Bao" "Dalia" "Elias")
                    ("Carlos" "Fatima" "Gustavo")
                    ("Dalia" "Hassan" "Isla")
                    ("Elias" "Javier")
                    ("Fatima" "Khadija" "Liam")
                    ("Gustavo" "Mina")
                    ("Hassan" "Noah" "Olga")
                    ("Isla" "Pedro")
                    ("Javier" "Quynh" "Ravi")
                    ("Khadija" "Sofia")
                    ("Liam" "Tariq" "Uma")
                    ("Mina" "Viktor" "Wang")
                    ("Noah" "Xiomara")
                    ("Olga" "Yuki")
                    ("Pedro" "Zane" "Aditi")
                    ("Quynh" "Boris")
                    ("Ravi" "Celine")
                    ("Sofia" "Diego" "Elif")
                    ("Tariq" "Farah")
                    ("Uma" "Giorgio")
                    ("Viktor" "Hana" "Ian")
                    ("Wang" "Jing")
                    ("Xiomara" "Kaito")
                    ("Yuki" "Leila")
                    ("Zane" "Mateo")
                    ("Aditi" "Nia")
                    ("Boris" "Oscar")
                    ("Celine" "Priya")
                    ("Diego" "Qi")
                    ("Elif" "Rami")
                    ("Farah" "Sven")
                    ("Giorgio" "Tomoko")
                    ("Hana" "Umar")
                    ("Ian" "Vera")
                    ("Jing" "Wyatt")
                    ("Kaito" "Xia")
                    ("Leila" "Yassin")
                    ("Mateo" "Zara")
                    ("Nia" "Antonio")
                    ("Oscar" "Bianca")
                    ("Priya" "Cai")
                    ("Qi" "Dimitri")
                    ("Rami" "Ewa")
                    ("Sven" "Fabio")
                    ("Tomoko" "Gabriela")
                    ("Umar" "Helena")
                    ("Vera" "Igor")
                    ("Wyatt" "Jun")
                    ("Xia" "Kim")
                    ("Yassin" "Lucia")
                    ("Zara" "Mohammed"))
                  "Lucia" "Jun"))))


(ert-deftest
    complex-graph-some-shortcuts-cross-down-and-cross-up-cousins-several-times-removed-with-unrelated-family-tree
    ()
  (should (= 12 (degree-of-separation '(
                    ("Aiko" "Bao" "Carlos")
                    ("Bao" "Dalia")
                    ("Carlos" "Fatima" "Gustavo")
                    ("Dalia" "Hassan" "Isla")
                    ("Fatima" "Khadija" "Liam")
                    ("Gustavo" "Mina")
                    ("Hassan" "Noah" "Olga")
                    ("Isla" "Pedro")
                    ("Javier" "Quynh" "Ravi")
                    ("Khadija" "Sofia")
                    ("Liam" "Tariq" "Uma")
                    ("Mina" "Viktor" "Wang")
                    ("Noah" "Xiomara")
                    ("Olga" "Yuki")
                    ("Pedro" "Zane" "Aditi")
                    ("Quynh" "Boris")
                    ("Ravi" "Celine")
                    ("Sofia" "Diego" "Elif")
                    ("Tariq" "Farah")
                    ("Uma" "Giorgio")
                    ("Viktor" "Hana" "Ian")
                    ("Wang" "Jing")
                    ("Xiomara" "Kaito")
                    ("Yuki" "Leila")
                    ("Zane" "Mateo")
                    ("Aditi" "Nia")
                    ("Boris" "Oscar")
                    ("Celine" "Priya")
                    ("Diego" "Qi")
                    ("Elif" "Rami")
                    ("Farah" "Sven")
                    ("Giorgio" "Tomoko")
                    ("Hana" "Umar")
                    ("Ian" "Vera")
                    ("Jing" "Wyatt")
                    ("Kaito" "Xia")
                    ("Leila" "Yassin")
                    ("Mateo" "Zara")
                    ("Nia" "Antonio")
                    ("Oscar" "Bianca")
                    ("Priya" "Cai")
                    ("Qi" "Dimitri")
                    ("Rami" "Ewa")
                    ("Sven" "Fabio")
                    ("Tomoko" "Gabriela")
                    ("Umar" "Helena")
                    ("Vera" "Igor")
                    ("Wyatt" "Jun")
                    ("Xia" "Kim")
                    ("Yassin" "Lucia")
                    ("Zara" "Mohammed"))
                  "Wyatt" "Xia"))))


(provide 'relative-distance-test)
;;; relative-distance-test.el ends here
